---
#####################################################
# 1) 패키지 설치 - NFS 서버 & 방화벽 설치
# 2) 서비스 설정 - 공유 디렉토리 생성 및 파일 배포
# 3) 서비스 기동 - rpcbind, nfs-server
# 4) 방화벽 등록
#####################################################
- name: 1) NFS 서버 & 방화벽 설치
  ansible.builtin.yum:
    name:
      - nfs-utils
      - firewalld
    state: present

- name: 2) 웹/CGI용 NFS 공유 디렉토리 생성
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ nfs_export }}"
    - "{{ nfs_export }}/cgi-bin"

- name: 2) /etc/exports 파일 전체 관리
  ansible.builtin.template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: '0644'
  notify: 서비스 기동 재시작


- name: 2) index.html 배포
  ansible.builtin.template:
    src: index.html.j2
    dest: "{{ nfs_export }}/index.html"
    owner: root
    group: root
    mode: '0644'

- name: 2) CGI 스크립트 배포
  ansible.builtin.template:
    src: test.cgi.j2
    dest: "{{ nfs_export }}/cgi-bin/test.cgi"
    owner: root
    group: root
    mode: '0755'

- name: 3) 서비스 기동
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - rpcbind
    - nfs-server
    - firewalld

- name: 4) 방화벽 등록
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  loop:
    - rpc-bind
    - nfs
    - mountd

